appName: nginx-2

# only for helm type application
helmChart:
  name: nginx
  repoURL: git@github.com:lowc1012/argo-lab.git
  version: HEAD
  valueFiles: "values.yaml test.yaml"

notification:
  slack:
    channels: []

cluster:
  name: in-cluster
  namespace: nginx-test
