appName: nginx

# only for helm type application
helmChart:
  name: nginx
  repoURL: git@github.com:lowc1012/argo-lab.git
  version: HEAD
  valueFiles: [ "values.yaml" ]

notification:
  slack:
    channels: [ "test-deployment", "team-b-deployment" ]

cluster:
  name: in-cluster
  namespace: nginx
