apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: team-a
  sources:
    - repoURL: git@github.com:lowc1012/argo-lab.git
      path: charts/nginx
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/apps/team-a/staging/nginx/values.yaml
    - repoURL: git@github.com:lowc1012/argo-lab.git
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  destination:
    namespace: nginx
    name: in-cluster
