apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:lowc1012/argo-lab.git
      path: charts/nginx
      targetRevision: HEAD
      helm:
        releaseName: nginx
        valueFiles:
          - $values/apps/team-a/production/nginx/values.yaml
    - repoURL: git@github.com:lowc1012/argo-lab.git
      targetRevision: HEAD
      ref: values
  
  destination:
    namespace: nginx
